### ISSUE TITLE
Initialize React Web Extension

### ISSUE THREAD

**Issue by cdrani** [cdrani/cadence#1]
Create React web extension. We will start with only a popup UI for now.

REF:

I used the below for a svelte web extension, so it should work just as well for a react one. Make sure to use the latest [beta release](https://github.com/crxjs/chrome-extension-tools/releases) version.

https://crxjs.dev/vite-plugin

**Comment by sstephanyy** [comment]
@cdrani: Solved this issue  -> e2f4c2d04641a06db8301ff80235009c20dd95de
